# Generated by Django 5.0.7 on 2024-08-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRequests',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('service_used', models.CharField(max_length=20)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'player_requests',
                'managed': True,
                'indexes': [models.Index(fields=['username'], name='username')],
            },
        ),
    ]
